export const products = [
  {
    id: 0,
    name: 'Tuna Filet',
    type: 'Fish',
    price: 25,
    description: 'The Tuna Filet is a delicacy renowned for its exquisite flavor and tender texture. Sourced from the finest ocean waters, this succulent cut of fish offers a rich, buttery taste that melts in your mouth. Whether grilled, seared, or enjoyed raw in sushi, the Tuna Filet is a true culinary indulgence.',
    descriptionsmall: 'The Tuna Filet is a delicacy renowned for its exquisite flavor and tender texture.',
    availab: true,
    image: "./assets/t4.png",
    imageReal: "./assets/t4.png",
    quantity: 0,
  },
  {
    id: 1,
    name: 'Pasta Cabonara',
    type: 'Pasta',
    price: 14,
    description: 'Pasta carbonara is a delectable Italian dish that combines al dente spaghetti, crispy bacon, creamy eggs, Parmesan cheese, and a touch of black pepper. Its rich flavors and velvety texture make it an irresistible comfort food. Whether enjoyed for lunch or dinner, pasta carbonara is a timeless classic that satisfies cravings with every bite.',
    descriptionsmall: 'Italian dish that combines al dente spaghetti, crispy bacon, creamy eggs, Parmesan, bit of black pepper.',
    availab: true,
    image: './assets/2.png',
    imageReal: "./assets/2.png",
    quantity: 0,
  },
  {
    id: 2,
    name: 'Pizza Codefactory',
    type: 'Pizza',
    price: 15,
    description: 'Indulge in the perfect combination of savory flavors with a delicious pizza salami. Each bite offers a symphony of zesty tomato sauce, gooey mozzarella cheese, and generous slices of mouthwatering salami. The crispy crust adds a satisfying crunch, making this classic pizza a true delight for your taste buds.',
    descriptionsmall: 'Each bite offers a symphony of zesty tomato sauce, gooey mozzarella cheese, and generous slices of mouthwatering salami.',
    availab: false,
    image: './assets/3.png',
    imageReal: "./assets/3.png",
    quantity: 0,
  }, {
    id: 3,
    name: 'IceCream',
    type: 'Desert',
    price: 9,
    description: 'Italian ice cream, known as gelato, is a delectable frozen treat loved worldwide. It is characterized by its smooth and creamy texture, intense flavors, and artisanal craftsmanship. Made with high-quality ingredients like fresh milk, fruits, and nuts, gelato offers a wide range of flavors, from classic favorites like chocolate and vanilla to unique creations like pistachio and stracciatella. Its lower fat content and dense consistency make gelato a delightful indulgence that captures the essence of Italian culinary excellence.',
    descriptionsmall: 'Italian ice cream, known as gelato, is a delectable frozen treat loved worldwide.',
    availab: true,
    image: "./assets/7.png",
    imageReal: "./assets/7.png",
    quantity: 0,
  },
  {
    id: 4,
    name: 'Filet Mignon',
    type: 'Exclusiv',
    price: 35,
    description: 'Filet mignon is a tender and highly prized cut of beef known for its exceptional tenderness and delicate flavor. It is taken from the tenderloin, a muscle located along the spine. Filet mignon is often considered the most luxurious steak, renowned for its melt-in-your-mouth texture and subtle, buttery richness. It is commonly served grilled or pan-seared and pairs well with savory sauces and accompaniments.',
    descriptionsmall: 'Filet mignon is a tender and highly prized cut of beef known for its exceptional tenderness and delicate flavor.',
    availab: false,
    image: './assets/5.png',
    imageReal: "./assets/5.png",
    quantity: 0,
  },
  {
    id: 5,
    name: 'Lasagne Codefactory',
    type: 'Pasta',
    price: 22,
    description: 'Italian lasagne is a classic and beloved dish known for its layers of tender pasta sheets, rich meat or vegetable sauce, creamy béchamel, and gooey melted cheese. This hearty and flavorful Italian favorite is often seasoned with aromatic herbs and spices, creating a satisfying and comforting meal that brings people together.',
    descriptionsmall: 'Italian lasagne is a classic and beloved dish all over the World.',
    availab: true,
    image: './assets/6.png',
    imageReal: "./assets/6.png",
    quantity: 0,
  }
];